
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'lineASSIGN COLON COMMA CONSTANT HEX_LITERAL IDENTIFIER INT LBRACK LPAREN PHI RBRACK RPAREN VARIABLEline : instruction\n            | phi_instructioninstruction : INT LBRACK HEX_LITERAL RBRACK COLON expressionphi_instruction : VARIABLE ASSIGN PHI LPAREN arg_list RPARENexpression : assignment\n                  | value_expressionassignment : VARIABLE ASSIGN valuevalue_expression : valuevalue : function_call\n             | standalone_valuefunction_call : IDENTIFIER LPAREN arg_list RPAREN\n                     | IDENTIFIER LPAREN RPARENstandalone_value : VARIABLE\n                        | CONSTANT\n                        | IDENTIFIERarg_list : arg_list COMMA arg\n                | argarg : any_constant\n           | VARIABLE\n           | function_call\n           | INTany_constant : CONSTANT\n                    | HEX_LITERAL'
    
_lr_action_items = {'INT':([0,11,32,33,],[4,18,18,18,]),'VARIABLE':([0,11,12,32,33,34,],[5,13,25,13,13,38,]),'$end':([1,2,3,22,23,24,25,26,27,28,29,30,31,37,38,39,40,],[0,-1,-2,-3,-5,-6,-13,-8,-9,-10,-15,-14,-4,-12,-13,-7,-11,]),'LBRACK':([4,],[6,]),'ASSIGN':([5,25,],[7,34,]),'HEX_LITERAL':([6,11,32,33,],[8,20,20,20,]),'PHI':([7,],[9,]),'RBRACK':([8,],[10,]),'LPAREN':([9,21,29,],[11,33,33,]),'COLON':([10,],[12,]),'CONSTANT':([11,12,32,33,34,],[19,30,19,19,30,]),'IDENTIFIER':([11,12,32,33,34,],[21,29,21,21,29,]),'RPAREN':([13,14,15,16,17,18,19,20,33,35,36,37,40,],[-19,31,-17,-18,-20,-21,-22,-23,37,-16,40,-12,-11,]),'COMMA':([13,14,15,16,17,18,19,20,35,36,37,40,],[-19,32,-17,-18,-20,-21,-22,-23,-16,32,-12,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'instruction':([0,],[2,]),'phi_instruction':([0,],[3,]),'arg_list':([11,33,],[14,36,]),'arg':([11,32,33,],[15,35,15,]),'any_constant':([11,32,33,],[16,16,16,]),'function_call':([11,12,32,33,34,],[17,27,17,17,27,]),'expression':([12,],[22,]),'assignment':([12,],[23,]),'value_expression':([12,],[24,]),'value':([12,34,],[26,39,]),'standalone_value':([12,34,],[28,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> instruction','line',1,'p_line','ssa_parser_ply.py',54),
  ('line -> phi_instruction','line',1,'p_line','ssa_parser_ply.py',55),
  ('instruction -> INT LBRACK HEX_LITERAL RBRACK COLON expression','instruction',6,'p_instruction','ssa_parser_ply.py',60),
  ('phi_instruction -> VARIABLE ASSIGN PHI LPAREN arg_list RPAREN','phi_instruction',6,'p_phi_instruction','ssa_parser_ply.py',69),
  ('expression -> assignment','expression',1,'p_expression','ssa_parser_ply.py',78),
  ('expression -> value_expression','expression',1,'p_expression','ssa_parser_ply.py',79),
  ('assignment -> VARIABLE ASSIGN value','assignment',3,'p_assignment','ssa_parser_ply.py',84),
  ('value_expression -> value','value_expression',1,'p_value_expression','ssa_parser_ply.py',91),
  ('value -> function_call','value',1,'p_value','ssa_parser_ply.py',98),
  ('value -> standalone_value','value',1,'p_value','ssa_parser_ply.py',99),
  ('function_call -> IDENTIFIER LPAREN arg_list RPAREN','function_call',4,'p_function_call','ssa_parser_ply.py',107),
  ('function_call -> IDENTIFIER LPAREN RPAREN','function_call',3,'p_function_call','ssa_parser_ply.py',108),
  ('standalone_value -> VARIABLE','standalone_value',1,'p_standalone_value','ssa_parser_ply.py',117),
  ('standalone_value -> CONSTANT','standalone_value',1,'p_standalone_value','ssa_parser_ply.py',118),
  ('standalone_value -> IDENTIFIER','standalone_value',1,'p_standalone_value','ssa_parser_ply.py',119),
  ('arg_list -> arg_list COMMA arg','arg_list',3,'p_arg_list','ssa_parser_ply.py',127),
  ('arg_list -> arg','arg_list',1,'p_arg_list','ssa_parser_ply.py',128),
  ('arg -> any_constant','arg',1,'p_arg','ssa_parser_ply.py',134),
  ('arg -> VARIABLE','arg',1,'p_arg','ssa_parser_ply.py',135),
  ('arg -> function_call','arg',1,'p_arg','ssa_parser_ply.py',136),
  ('arg -> INT','arg',1,'p_arg','ssa_parser_ply.py',137),
  ('any_constant -> CONSTANT','any_constant',1,'p_any_constant','ssa_parser_ply.py',142),
  ('any_constant -> HEX_LITERAL','any_constant',1,'p_any_constant','ssa_parser_ply.py',143),
]
